# Generated by Django 5.0.3 on 2025-04-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('producto_recomendado', models.CharField(max_length=255)),
                ('imagen_url', models.URLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
