# Generated by Django 5.1.6 on 2025-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
